/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package notifier;

public class App {
    public static final Configuration config = new Configuration();
    public static final DB database = new DB();

    public static void main(String[] args) {
        database.createTables();
        database.updateDomains();
        database.updateServers();
        Healthcheck healthcheck = new Healthcheck(database.getDomains(), 4);
        Ping ping = new Ping(database.getIPs(), 4);
        Thread healthcheck_thread = new Thread(healthcheck::healthcheckLoop);
        Thread ping_thread = new Thread(ping::pingLoop);
        healthcheck_thread.start();
        ping_thread.start();
    }
}
